[project]
name = "atcoder-local"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "aclogin>=0.2.1",
    "online-judge-tools>=11.5.1",
]
